// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.linux:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.windows:
        // TODO: Handle this case.
        throw UnimplementedError();
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_sn54Ck06nJGmvMb1WOSi-c3asZz-knA',
    appId: '1:516522501900:web:943d37aa2d24a852758b29',
    messagingSenderId: '516522501900',
    projectId: 'quizapp-968f8',
    authDomain: 'quizapp-968f8.firebaseapp.com',
    storageBucket: 'quizapp-968f8.firebasestorage.app',
    measurementId: 'G-VYK840514R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMbpPf5X7HjOsPU2BDEIP58TppuBflrI',
    appId: '1:516522501900:android:9c03c3b9136ae6fb758b29',
    messagingSenderId: '516522501900',
    projectId: 'quizapp-968f8',
    storageBucket: 'quizapp-968f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWWDh3PozhHrYrRXzzqeExwFHPhoZdQ-Q',
    appId: '1:516522501900:ios:3fd0163afcff4b7b758b29',
    messagingSenderId: '516522501900',
    projectId: 'quizapp-968f8',
    storageBucket: 'quizapp-968f8.firebasestorage.app',
    iosClientId: '516522501900-v5f45d4kb1rvjfhqp9gldh8k9u7q2q3e.apps.googleusercontent.com',
    iosBundleId: 'com.prashant.quiz.app',
  );

}